
all:
	g++ mss.cpp -fopenmp -o mss
	g++ msp.cpp -fopenmp -o msp
	g++ qss.cpp -fopenmp -o qss
	g++ qsp.cpp -fopenmp -o qsp
	g++ reference.cpp -fopenmp -o reference
	g++ bbs.cpp -fopenmp -o bbs
	g++ bbp.cpp -fopenmp -o bbp
